name: flutter_sqflite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  synchronized: ^3.1.0+1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
